<?php
/**
 * Created by PhpStorm.
 * Author: hlh XueSi
 * Email: 1592328848@qq.com
 * Date: 2022/4/14 17:40:17
 */

namespace LavaMusic\ElasticSearch\Tests;

define('ELASTICSEARCH_SERVER_HOST', 'localhost');
define('ELASTICSEARCH_SERVER_PORT', 9200);

use LavaMusic\ElasticSearch\Client;
use LavaMusic\ElasticSearch\ClientBuilder;
use PHPUnit\Framework\TestCase;

class BaseTestCase extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        error_reporting(E_ALL | E_STRICT);

        // Set the default timezone. While this doesn't cause any tests to fail, PHP
        // complains if it is not set in 'date.timezone' of php.ini.
        date_default_timezone_set('UTC');
    }

    public function createClient(string $scheme = 'http')
    {
        $hosts = [
            $scheme . '://' . ELASTICSEARCH_SERVER_HOST . ':' . ELASTICSEARCH_SERVER_PORT,
        ];
        return ClientBuilder::create()
            ->setHosts($hosts)
            ->build();
    }
}